### ISSUE TITLE
A quick init command would be nice

### ISSUE THREAD

**Issue by sebgoa** [carvel-dev/imgpkg#183] opened 2021-07-06 09:37 UTC
**Describe the problem/challenge you have**

I want to get started quickly with `imgpkg` , the examples make me create a directory, a sub directory and then add some files. That is suboptimal

**Describe the solution you'd like**

I would have loved a quick `imgpkg init` which would have created the skeleton including a basic `images.yml` file

**Comment by ewrenn8** [comment] 2021-07-06 13:26
Duplicate of #61

**Closed as completed by ewrenn8** 2021-07-06 13:26 UTC
Labels: enhancement
